# Generated by Django 3.2.4 on 2021-06-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
