# Generated by Django 3.2.4 on 2021-06-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='realized_load',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='load',
            name='target_load',
            field=models.IntegerField(default=0),
        ),
    ]
