# Generated by Django 3.2.4 on 2021-06-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_alter_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='calendar_app',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.calendarapp'),
        ),
        migrations.AlterField(
            model_name='note',
            name='doing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.doing'),
        ),
        migrations.AlterField(
            model_name='note',
            name='realize_step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.realizestep'),
        ),
    ]
