# Generated by Django 3.2.4 on 2021-06-12 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_alter_loadmeasurementtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizestep',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='realizestep',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
