# Generated by Django 3.2.4 on 2021-06-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20210612_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizestep',
            name='end_time',
            field=models.TimeField(blank=True, default=(2021, 6, 12, 9, 19, 26, 5, 163, 0), null=True),
        ),
        migrations.AlterField(
            model_name='realizestep',
            name='start_time',
            field=models.TimeField(blank=True, default=(2021, 6, 12, 9, 19, 26, 5, 163, 0), null=True),
        ),
    ]
