# Generated by Django 3.2.4 on 2021-06-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_auto_20210612_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizestep',
            name='end_time',
            field=models.TimeField(blank=True, default='09:21', null=True),
        ),
        migrations.AlterField(
            model_name='realizestep',
            name='start_time',
            field=models.TimeField(blank=True, default='09:21', null=True),
        ),
    ]
