# Generated by Django 3.2.4 on 2021-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_auto_20210612_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizestep',
            name='end_time',
            field=models.TimeField(blank=True, default='18:22', null=True),
        ),
        migrations.AlterField(
            model_name='realizestep',
            name='start_time',
            field=models.TimeField(blank=True, default='18:22', null=True),
        ),
    ]
